# Generated by Django 4.1.3 on 2022-11-24 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Название тега')),
                ('slug', models.SlugField(unique=True, verbose_name='Слаг тега')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Works',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/works', verbose_name='Фото работы')),
                ('tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='works', to='products.tag', verbose_name='Теги')),
            ],
            options={
                'verbose_name': 'Моя работа',
                'verbose_name_plural': 'Мои работы',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название изделия')),
                ('image', models.ImageField(upload_to='products/cakes/', verbose_name='Фото готового изделия')),
                ('description', models.TextField(verbose_name='Описание изделия')),
                ('limits', models.TextField(blank=True, verbose_name='Дополнение')),
                ('price', models.PositiveIntegerField(verbose_name='Цена')),
                ('extra_price', models.PositiveIntegerField(blank=True, default=0, verbose_name='Дополнитьельная цена')),
                ('measurement_unit', models.CharField(max_length=100, verbose_name='Единица изделия')),
                ('tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tags', to='products.tag', verbose_name='Теги')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ExtraPhotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='products/extra', verbose_name='Дополнительные фото')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_photos', to='products.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Дополнительное фото',
                'verbose_name_plural': 'Дополнительные фото',
                'ordering': ['-id'],
            },
        ),
    ]
